### ISSUE TITLE
Changelog oder ReleaseNotes?

### ISSUE THREAD

**Issue by karfau** [jverein/jverein#17]
Da die Tickets und der Code ja nun nach github gewandert sind (:+1: ) sollte es auch die Möglichkeit geben zu erfahren was in einer neuen Version drin ist.

Es gibt hier bei github zwei übliche Vorgehensweisen dafür:

- eine Datei im root Verzeichnis des Projekts z.B. `CHANGELOG.md` die mit jeder neuen Version aktualisiert wird.
- eine github spezifische Lösung: https://github.com/jverein/jverein/releases Dort kann ein neues Release markiert werden, es wird dann automatisch ein tag erstellt.

Der einzige Weg um sonst rauszukriegen was passiert ist, bleibt natürlich https://github.com/jverein/jverein/commits/master

**Comment by karfau** [comment]
Ich habe gerade entdeckt das es bei hibiscus etwas gibt, das automatisiert aussieht:

https://github.com/willuhn/hibiscus/blob/master/build/ChangeLog

Sicherlich lässt sich das auch für jverein umsetzen.

**Comment by jverein** [comment]
Reicht dir https://github.com/jverein/jverein/releases nicht aus?

**Comment by karfau** [comment]
Das würde mir reichen wenn die aktuelle Version (mir wurde neulich ) da auch aufgeführt werden würde.
Und es wäre noch toller, wenn es eine kurze Zusammenfassung geben würde, was es in der Version Neues gibt.
