### ISSUE TITLE
Spenden Dauerauftrag Buttons fehlen

### ISSUE THREAD

**Issue by DGUF** [jverein/jverein#21]
Möchte man einen Spenden-Dauerauftrag für JVerein anlegen, fehlen entsprechende Buttons zum Speichern / Ausführen o. ä.

**Comment by jverein** [comment]
Da war noch der alte Dauerauftrag mit BLZ und Kontonummer drin. Das habe ich jetzt zum SEPA-Dauerauftrag umgestellt.
