### ISSUE TITLE
Gitbook - Thema "Variable" fehlt

### ISSUE THREAD

**Issue by nilsnerd** [jverein/jverein#22]
Der Link im Gitbook im Kapitel "Buchführung --> Buchungsimport" funktioniert nicht: https://jverein.gitbooks.io/jverein-handbuch/content/buchungsvariable.md 

Die Inhalte: http://www.jverein.de/wiki/index.php?title=Variable scheinen nicht aus dem wiki übernommen worden zu sein.
Grüße
Nils

**Comment by jverein** [comment]
Den Link von Buchungsimport zu Variablen habe ich korrigiert. Die Variablen werden unter https://jverein.gitbooks.io/jverein-handbuch/content/variable.html beschrieben.
