### ISSUE TITLE
Hostname auf localhost gesetzt

### ISSUE THREAD

**Issue by PhilmacFLy** [jverein/jverein#23]
Die Mail Implementierung scheint beim Versand den hostnamen nicht zu setzten, da ich im log meines Mail servers folgendes seh:
`Mar 14 22:05:01 lithium postfix/smtpd[6343]: NOQUEUE: reject_warning: RCPT from erx-rz.binary-kitchen.net[213.166.246.250]: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname; from=<vorstand@binary-kitchen.de> to=<jverein@philmacfly.eu> proto=ES
MTP helo=<localhost>`

**Comment by jverein** [comment]
Hast du den Mailserver korrekt konfiguriert?

**Comment by PhilmacFLy** [comment]
Ja hab ich

**Comment by jverein** [comment]
Ich habe mir gerade den Quelltext angesehen. Der Name des SMTP-Servers wird korrekt übertragen. Du hast ein lokales Problem. Wenn es generell nicht laufen würde, gäbe es jede Menge Tickets zu dem Thema
