### ISSUE TITLE
Plugin fails to load with version 2.8.2 of jameica

### ISSUE THREAD

**Issue by karfau** [jverein/jverein#31]
After updating to [jameica version 2.8.2](https://github.com/willuhn/jameica/releases/tag/V_2_8_2_BUILD_450)
Loading the plugin failed with an error.

I was able to recover to version 2.8.1 and I'm currently not able to find a log file that contains more details.

If required I can install that version again, but I would prefer not to do it.

**Comment by karfau** [comment]
This is my logfile with the current version again, hopefully somebody can help me to understand-debug the issue based  on this data.
[jameica-20180921.log](https://github.com/jverein/jverein/files/2407169/jameica-20180921.log)

best Christian

**Comment by karfau** [comment]
As mentioned in the comments of the release notes, https://www.willuhn.de/blog/index.php?/archives/785-Jameica-2.8.2.html#comments
JVerein can currently not run with the distributed h2 version 1.4.197(snapshot).
I resolved the issue by downgrading to http://central.maven.org/maven2/com/h2database/h2/1.4.196/h2-1.4.196.jar

**Comment by karfau** [comment]
Da ich das Problem nur für mich gelöst habe und es für alle anderen noch besteht, öffne ich den issue wieder.

**Comment by jverein** [comment]
Der Lösungsansatz bleibt der gleiche. Es gibt noch keinen neueren H2-Treiber. Entweder du nutzt den Treiber, der in der aktuellen Jameica-Version drin ist oder du musst den älteren , wie beschrieben verwenden. Falls das nicht hilft, liegt bei dir evtl. ein anderes Problem vor.
