### ISSUE TITLE
Anbindung an SportBizz (Bestandserhebung Sportbünde)

### ISSUE THREAD

**Issue by leofuehringer** [jverein/jverein#35]
Hallo zusammen,
ich würde gerne für JVerein eine Integration an das SportBizz implementieren, so dass die jährlich 
an die Sportbünde zu meldenden Mitglieder (Bestandserhebung) einfach als "passende" xml-Datei exportiert und im SportBizz (z.B. BSB-Net) importiert werden können. Das betrifft sicherlich viele Vereine und wäre daher in meinen Augen eine gute Erweiterung.

Nun möchte ich jedoch fragen, wie ich das realisieren soll. Als extra Plugin für Jameica oder direkt als Fork in Git für JVerein?

Die Schnittstelle von Seitens des SportBizz ist gut dokumentiert:
[Schnittstelle_Integration_Vereinsverwaltung_ab_2014_.pdf](https://github.com/jverein/jverein/files/2820522/Schnittstelle_Integration_Vereinsverwaltung_ab_2014_.pdf)
[DOSB_Fachverbandskodierung_Version_2013_.pdf](https://github.com/jverein/jverein/files/2820524/DOSB_Fachverbandskodierung_Version_2013_.pdf)

Liebe Grüße,
Leo

**Comment by jverein** [comment]
Du kannst das direkt in JVerein realisieren.
