### ISSUE TITLE
JVerein Datenbank lässt sich nicht mit Jameica 2.8.4 und Hibiscus 2.8.10 öffnen

### ISSUE THREAD

**Issue by florian-rabis** [jverein/jverein#41]
Hallo,
ich habe folgendes Problem. Unsere JVerein-Datenbank lässt sich leider nicht mit einer neueren Version von Jamaica oder Hibiscus öffnen.
Wir haben verschiedene Versionen ausprobiert. Die letzte funktionierende Konfiguration ist:
Jameica: 2.6.6
Hibiscus: 2.6.20
JVerein: 2.8.17

Hier noch das Diagnose-Protokoll.

[diagnose-2019-03-01.log](https://github.com/jverein/jverein/files/2917460/diagnose-2019-03-01.log)

Vielen Dank und Beste Grüße

**Comment by vore** [comment]
Hallo! Ich habe das gleiche Problem. Gibt es schon eine Lösung?
Danke!

**Comment by karfau** [comment]
Seit ich wie in #34 berichtet mit dem Drucken von PDF Probleme hatte, habe ich meine Versionen nicht mehr aktualisiert.
Bei mir ist es Jameica 2.8.2 und Hibiscus 2.8.8 (auch mit JVerein 2.8.17)
Allerdings weiß ich im Moment noch nicht wie man an diese Versionen von Jameica und Hibiscus rankommt wenn man sie nicht schon hat.

**Comment by jverein** [comment]
Problem sollte inzwischen behoben sein. Falls es doch noch besteht, Ticket wieder eröffnen
