### ISSUE TITLE
$lastschrift_betrag falsch formatiert

### ISSUE THREAD

**Issue by htgoebel** [jverein/jverein#44]
Die Variable `$lastschrift_betrag` wird in pre-notification Mails nicht so formatiert, wie man es erwarten würde:

Ausgabe: `100.0` (Punkt als Dezimaltrennzeichen, 1 Nachkommestelle)
Erwartet: `100,00` (Komma als Dezimaltrennzeichen, 2 Nachkommastellen)

**Comment by jverein** [comment]
Erledigt
