### ISSUE TITLE
Versionen taggen

### ISSUE THREAD

**Issue by ford--prefect** [jverein/jverein#7]
Hallo,
es wäre total praktisch, wenn die Versionen auf Github getaggt würden, dann könnte man die vorhandene Infrastruktur hier nutzen.
Vielen Dank!

**Comment by jverein** [comment]
Zu Silvester wurde die erste Version seit dem Umzug zu Github herausgegeben. Gerade habe ich getagged.

**Comment by ford--prefect** [comment]
Ach wunderbar. Herzlichen Dank und  gesundes Neues.
-- 
https://gehsicht.de
