### ISSUE TITLE
Formular Spendenbescheinigung lässt sich nicht ändern.

### ISSUE THREAD

**Issue by mbmueller** [jverein/jverein#82]
Ich habe ein neues Formular für Spendenbescheinigungen erstellt, allerdings bleibt immer das alte erhalten. Habe auch schon probiert das ganze komplett neu zu erstellen. Ging alles nicht.
Da ich leider nicht weiß unter welchen Dateipfad die Dokumente gespeichert werden, kann ich das alte Formular nicht manuell löschen.

**Comment by MichlS84** [comment]
Hast du eine neue Spendenbescheinigung über "neu (manuell)" oder "neu (automatisch)" erstellt?

**Comment by mbmueller** [comment]
Über das Mitgliedskonto

**Comment by MichlS84** [comment]
Also bei mir funktioniert das. Bist du nach der Anleitung vorgegangen:
https://doku.jverein.de/allgemeine-funktionen/administration/formulare

Also zuerst ein PDF ohne Formularfelder erstellen. Anschließend die Felder hinzugefügt.

Beim Mitglied dann auf den Button "PDF individuell" gedrückt?

**Comment by mbmueller** [comment]
Bei mir gings dann komischerweise auch.,,
